using UnityEngine;

namespace UbiArt.ITF {
	public partial class Ray_GroundAIComponent_Template : Ray_AIComponent_Template {
		[Serialize("roamBehavior"                    )] public Placeholder roamBehavior;
		[Serialize("runAwayBehavior"                 )] public Placeholder runAwayBehavior;
		[Serialize("attackBehavior"                  )] public Placeholder attackBehavior;
		[Serialize("receiveHitBehavior"              )] public Placeholder receiveHitBehavior;
		[Serialize("deathBehavior"                   )] public Placeholder deathBehavior;
		[Serialize("crushedBehavior"                 )] public Placeholder crushedBehavior;
		[Serialize("darktoonedBehavior"              )] public Placeholder darktoonedBehavior;
		[Serialize("undarktoonifyBehavior"           )] public Placeholder undarktoonifyBehavior;
		[Serialize("sleepBehavior"                   )] public Placeholder sleepBehavior;
		[Serialize("spawnBehavior"                   )] public Placeholder spawnBehavior;
		[Serialize("floatBehavior"                   )] public Placeholder floatBehavior;
		[Serialize("closeRangeAttackBehavior"        )] public Placeholder closeRangeAttackBehavior;
		[Serialize("hitWallBehavior"                 )] public Placeholder hitWallBehavior;
		[Serialize("enemyDetectionRange"             )] public Placeholder enemyDetectionRange;
		[Serialize("enemyChangeRange"                )] public Placeholder enemyChangeRange;
		[Serialize("closeRangeAttackDetectionRange"  )] public Placeholder closeRangeAttackDetectionRange;
		[Serialize("keepRunningAwayRange"            )] public float keepRunningAwayRange;
		[Serialize("runAwayTime"                     )] public float runAwayTime;
		[Serialize("runAwayEnemyLimit"               )] public uint runAwayEnemyLimit;
		[Serialize("wakeUpOnEnemyDetection"          )] public bool wakeUpOnEnemyDetection;
		[Serialize("wakeUpOnCloseEnemyDetection"     )] public bool wakeUpOnCloseEnemyDetection;
		[Serialize("roamTime"                        )] public float roamTime;
		[Serialize("sleepTime"                       )] public float sleepTime;
		[Serialize("canDetectEnemiesWhileSleeping"   )] public bool canDetectEnemiesWhileSleeping;
		[Serialize("darktoon"                        )] public Path darktoon;
		[Serialize("darktoonified"                   )] public bool darktoonified;
		[Serialize("darktoonificationBone"           )] public StringID darktoonificationBone;
		[Serialize("darktoonifiedHealth"             )] public uint darktoonifiedHealth;
		[Serialize("darktoonificationEjectionForceX" )] public float darktoonificationEjectionForceX;
		[Serialize("darktoonificationEjectionForceY" )] public float darktoonificationEjectionForceY;
		[Serialize("maxAttackDelay"                  )] public float maxAttackDelay;
		[Serialize("swimWaterResistMinSpeed"         )] public float swimWaterResistMinSpeed;
		[Serialize("swimWaterResistMaxSpeed"         )] public float swimWaterResistMaxSpeed;
		[Serialize("swimTopSpeed"                    )] public float swimTopSpeed;
		[Serialize("swimSurfaceRange"                )] public float swimSurfaceRange;
		[Serialize("swimTurnUpsideDownWait"          )] public float swimTurnUpsideDownWait;
		[Serialize("swimInertiaEnterDownMultiplier"  )] public float swimInertiaEnterDownMultiplier;
		[Serialize("swimInertiaEnterNormalMultiplier")] public float swimInertiaEnterNormalMultiplier;
		[Serialize("swimInertiaEnterMaxSpeed"        )] public float swimInertiaEnterMaxSpeed;
		[Serialize("swimInertiaSpeed"                )] public float swimInertiaSpeed;
		[Serialize("dominoHitShape"                  )] public Placeholder dominoHitShape;
		[Serialize("canRehit"                        )] public bool canRehit;
		[Serialize("dominoHitSpeedMultiplier"        )] public float dominoHitSpeedMultiplier;
		[Serialize("squashPenetrationRadius"         )] public float squashPenetrationRadius;
		protected override void SerializeImpl(CSerializerObject s) {
			base.SerializeImpl(s);
			SerializeField(s, nameof(roamBehavior));
			SerializeField(s, nameof(runAwayBehavior));
			SerializeField(s, nameof(attackBehavior));
			SerializeField(s, nameof(receiveHitBehavior));
			SerializeField(s, nameof(deathBehavior));
			SerializeField(s, nameof(crushedBehavior));
			SerializeField(s, nameof(darktoonedBehavior));
			SerializeField(s, nameof(undarktoonifyBehavior));
			SerializeField(s, nameof(sleepBehavior));
			SerializeField(s, nameof(spawnBehavior));
			SerializeField(s, nameof(floatBehavior));
			SerializeField(s, nameof(closeRangeAttackBehavior));
			SerializeField(s, nameof(hitWallBehavior));
			SerializeField(s, nameof(enemyDetectionRange));
			SerializeField(s, nameof(enemyChangeRange));
			SerializeField(s, nameof(closeRangeAttackDetectionRange));
			SerializeField(s, nameof(keepRunningAwayRange));
			SerializeField(s, nameof(runAwayTime));
			SerializeField(s, nameof(runAwayEnemyLimit));
			SerializeField(s, nameof(wakeUpOnEnemyDetection));
			SerializeField(s, nameof(wakeUpOnCloseEnemyDetection));
			SerializeField(s, nameof(roamTime));
			SerializeField(s, nameof(sleepTime));
			SerializeField(s, nameof(canDetectEnemiesWhileSleeping));
			SerializeField(s, nameof(darktoon));
			SerializeField(s, nameof(darktoonified));
			SerializeField(s, nameof(darktoonificationBone));
			SerializeField(s, nameof(darktoonifiedHealth));
			SerializeField(s, nameof(darktoonificationEjectionForceX));
			SerializeField(s, nameof(darktoonificationEjectionForceY));
			SerializeField(s, nameof(maxAttackDelay));
			SerializeField(s, nameof(swimWaterResistMinSpeed));
			SerializeField(s, nameof(swimWaterResistMaxSpeed));
			SerializeField(s, nameof(swimTopSpeed));
			SerializeField(s, nameof(swimSurfaceRange));
			SerializeField(s, nameof(swimTurnUpsideDownWait));
			SerializeField(s, nameof(swimInertiaEnterDownMultiplier));
			SerializeField(s, nameof(swimInertiaEnterNormalMultiplier));
			SerializeField(s, nameof(swimInertiaEnterMaxSpeed));
			SerializeField(s, nameof(swimInertiaSpeed));
			SerializeField(s, nameof(dominoHitShape));
			SerializeField(s, nameof(canRehit));
			SerializeField(s, nameof(dominoHitSpeedMultiplier));
			SerializeField(s, nameof(squashPenetrationRadius));
		}
		public override uint? ClassCRC => 0x3A818BBC;
	}
}

