using UnityEngine;

namespace UbiArt.ITF {
	[Games(GameFlags.RA | GameFlags.VH | GameFlags.RJR | GameFlags.RFR)]
	public partial class CamModifier_Template : CSerializable {
		[Serialize("cameraLookAtOffsetYUp"                   )] public float cameraLookAtOffsetYUp;
		[Serialize("cameraLookAtOffsetYDown"                 )] public float cameraLookAtOffsetYDown;
		[Serialize("cameraLookAtOffset"                      )] public Vector3 cameraLookAtOffset;
		[Serialize("cameraLookAtOffsetMaxInMulti"            )] public Vector3 cameraLookAtOffsetMaxInMulti;
		[Serialize("focale"                                  )] public Angle focale;
		[Serialize("ignoreZ"                                 )] public bool ignoreZ;
		[Serialize("zoneScaleDepthMin"                       )] public float zoneScaleDepthMin;
		[Serialize("zoneScaleDepthMax"                       )] public float zoneScaleDepthMax;
		[Serialize("zoneScaleAtDepthMin"                     )] public Vector2 zoneScaleAtDepthMin;
		[Serialize("zoneScaleAtDepthMax"                     )] public Vector2 zoneScaleAtDepthMax;
		[Serialize("zoneScaleSpeed"                          )] public float zoneScaleSpeed;
		[Serialize("cameraDecenteringOffsetAtSpeedMin"       )] public Vector2 cameraDecenteringOffsetAtSpeedMin;
		[Serialize("cameraDecenteringOffsetAtSpeedMax"       )] public Vector2 cameraDecenteringOffsetAtSpeedMax;
		[Serialize("cameraDecenteringSpeedMin"               )] public Vector2 cameraDecenteringSpeedMin;
		[Serialize("cameraDecenteringSpeedMax"               )] public Vector2 cameraDecenteringSpeedMax;
		[Serialize("cameraDecenteringBlendAtSpeedMin"        )] public Vector2 cameraDecenteringBlendAtSpeedMin;
		[Serialize("cameraDecenteringBlendAtSpeedMax"        )] public Vector2 cameraDecenteringBlendAtSpeedMax;
		[Serialize("cameraDecenteringInertieAtSpeedMin"      )] public Vector2 cameraDecenteringInertieAtSpeedMin;
		[Serialize("cameraDecenteringInertieAtSpeedMax"      )] public Vector2 cameraDecenteringInertieAtSpeedMax;
		[Serialize("cameraDecenteringSmooth"                 )] public Vector2 cameraDecenteringSmooth;
		[Serialize("cameraDecenteringSubjectLookDirWeight"   )] public Vector2 cameraDecenteringSubjectLookDirWeight;
		[Serialize("cameraDecenteringDepthMin"               )] public float cameraDecenteringDepthMin;
		[Serialize("cameraDecenteringDepthMax"               )] public float cameraDecenteringDepthMax;
		[Serialize("cameraMovingSpeedMin"                    )] public Vector2 cameraMovingSpeedMin;
		[Serialize("cameraMovingSpeedMax"                    )] public Vector2 cameraMovingSpeedMax;
		[Serialize("cameraMovingBlendAtSpeedMin"             )] public Vector2 cameraMovingBlendAtSpeedMin;
		[Serialize("cameraMovingBlendAtSpeedMax"             )] public Vector2 cameraMovingBlendAtSpeedMax;
		[Serialize("cameraMovingSmooth"                      )] public Vector2 cameraMovingSmooth;
		[Serialize("cameraMovingBlendAccelerationJustSticked")] public float cameraMovingBlendAccelerationJustSticked;
		[Serialize("rayCastScaleMax"                         )] public float rayCastScaleMax;
		[Serialize("lockPositionBlendOnEnter"                )] public float lockPositionBlendOnEnter;
		[Serialize("lockPositionBlendOnExit"                 )] public float lockPositionBlendOnExit;
		[Serialize("screenLimitUpSpeedMax"                   )] public float screenLimitUpSpeedMax;
		[Serialize("screenLimitUpScale"                      )] public float screenLimitUpScale;
		[Serialize("subjectWeightUnregisterDelay"            )] public float subjectWeightUnregisterDelay;
		[Serialize("subjectWeightRegisterDelay"              )] public float subjectWeightRegisterDelay;
		[Serialize("subjectMainVisibilityHorizontal"         )] public Vector2 subjectMainVisibilityHorizontal;
		[Serialize("subjectMainVisibilityVertical"           )] public Vector2 subjectMainVisibilityVertical;
		[Serialize("cameraMovingSmoothCoeffForLeader"        )] public float cameraMovingSmoothCoeffForLeader;
		[Serialize("subjectMainVisibilitySwitchAxeSpeed"     )] public float subjectMainVisibilitySwitchAxeSpeed;
		[Serialize("zoomBlendInMultiplayer"                  )] public float zoomBlendInMultiplayer;
		[Serialize("isMainSubject"                           )] public bool isMainSubject;
		[Serialize("isMainDRCPlayer"                         )] public bool isMainDRCPlayer;
		[Serialize("isLockedAxe"                             )] public bool isLockedAxe;
		[Serialize("isFixed"                                 )] public bool isFixed;
		[Serialize("float__0"                                )] public float float__0;
		[Serialize("float__1"                                )] public float float__1;
		[Serialize("Vector3__2"                              )] public Vector3 Vector3__2;
		[Serialize("Vector3__3"                              )] public Vector3 Vector3__3;
		[Serialize("float__4"                                )] public float float__4;
		[Serialize("float__5"                                )] public float float__5;
		[Serialize("Vector3__6"                              )] public Vector3 Vector3__6;
		[Serialize("Vector3__7"                              )] public Vector3 Vector3__7;
		[Serialize("float__8"                                )] public float float__8;
		[Serialize("int__9"                                  )] public int int__9;
		[Serialize("float__10"                               )] public float float__10;
		[Serialize("float__11"                               )] public float float__11;
		[Serialize("Vector2__12"                             )] public Vector2 Vector2__12;
		[Serialize("Vector2__13"                             )] public Vector2 Vector2__13;
		[Serialize("float__14"                               )] public float float__14;
		[Serialize("Vector2__15"                             )] public Vector2 Vector2__15;
		[Serialize("Vector2__16"                             )] public Vector2 Vector2__16;
		[Serialize("Vector2__17"                             )] public Vector2 Vector2__17;
		[Serialize("Vector2__18"                             )] public Vector2 Vector2__18;
		[Serialize("Vector2__19"                             )] public Vector2 Vector2__19;
		[Serialize("Vector2__20"                             )] public Vector2 Vector2__20;
		[Serialize("Vector2__21"                             )] public Vector2 Vector2__21;
		[Serialize("Vector2__22"                             )] public Vector2 Vector2__22;
		[Serialize("Vector2__23"                             )] public Vector2 Vector2__23;
		[Serialize("Vector2__24"                             )] public Vector2 Vector2__24;
		[Serialize("Vector2__25"                             )] public Vector2 Vector2__25;
		[Serialize("float__26"                               )] public float float__26;
		[Serialize("float__27"                               )] public float float__27;
		[Serialize("Vector2__28"                             )] public Vector2 Vector2__28;
		[Serialize("Vector2__29"                             )] public Vector2 Vector2__29;
		[Serialize("Vector2__30"                             )] public Vector2 Vector2__30;
		[Serialize("Vector2__31"                             )] public Vector2 Vector2__31;
		[Serialize("Vector2__32"                             )] public Vector2 Vector2__32;
		[Serialize("float__33"                               )] public float float__33;
		[Serialize("float__34"                               )] public float float__34;
		[Serialize("float__35"                               )] public float float__35;
		[Serialize("float__36"                               )] public float float__36;
		[Serialize("float__37"                               )] public float float__37;
		[Serialize("float__38"                               )] public float float__38;
		[Serialize("float__39"                               )] public float float__39;
		[Serialize("float__40"                               )] public float float__40;
		[Serialize("Vector2__41"                             )] public Vector2 Vector2__41;
		[Serialize("Vector2__42"                             )] public Vector2 Vector2__42;
		[Serialize("float__43"                               )] public float float__43;
		[Serialize("float__44"                               )] public float float__44;
		[Serialize("float__45"                               )] public float float__45;
		[Serialize("float__46"                               )] public float float__46;
		[Serialize("float__47"                               )] public float float__47;
		[Serialize("float__48"                               )] public float float__48;
		[Serialize("float__49"                               )] public float float__49;
		[Serialize("float__50"                               )] public float float__50;
		[Serialize("float__51"                               )] public float float__51;
		[Serialize("int__52"                                 )] public int int__52;
		protected override void SerializeImpl(CSerializerObject s) {
			base.SerializeImpl(s);
			if (Settings.s.game == Settings.Game.RJR || Settings.s.game == Settings.Game.RFR) {
				SerializeField(s, nameof(float__0));
				SerializeField(s, nameof(float__1));
				SerializeField(s, nameof(Vector3__2));
				SerializeField(s, nameof(Vector3__3));
				SerializeField(s, nameof(float__4));
				SerializeField(s, nameof(float__5));
				SerializeField(s, nameof(Vector3__6));
				SerializeField(s, nameof(Vector3__7));
				SerializeField(s, nameof(float__8));
				SerializeField(s, nameof(int__9));
				SerializeField(s, nameof(float__10));
				SerializeField(s, nameof(float__11));
				SerializeField(s, nameof(Vector2__12));
				SerializeField(s, nameof(Vector2__13));
				SerializeField(s, nameof(float__14));
				SerializeField(s, nameof(Vector2__15));
				SerializeField(s, nameof(Vector2__16));
				SerializeField(s, nameof(Vector2__17));
				SerializeField(s, nameof(Vector2__18));
				SerializeField(s, nameof(Vector2__19));
				SerializeField(s, nameof(Vector2__20));
				SerializeField(s, nameof(Vector2__21));
				SerializeField(s, nameof(Vector2__22));
				SerializeField(s, nameof(Vector2__23));
				SerializeField(s, nameof(Vector2__24));
				SerializeField(s, nameof(Vector2__25));
				SerializeField(s, nameof(float__26));
				SerializeField(s, nameof(float__27));
				SerializeField(s, nameof(Vector2__28));
				SerializeField(s, nameof(Vector2__29));
				SerializeField(s, nameof(Vector2__30));
				SerializeField(s, nameof(Vector2__31));
				SerializeField(s, nameof(Vector2__32));
				SerializeField(s, nameof(float__33));
				SerializeField(s, nameof(float__34));
				SerializeField(s, nameof(float__35));
				SerializeField(s, nameof(float__36));
				SerializeField(s, nameof(float__37));
				SerializeField(s, nameof(float__38));
				SerializeField(s, nameof(float__39));
				SerializeField(s, nameof(float__40));
				SerializeField(s, nameof(Vector2__41));
				SerializeField(s, nameof(Vector2__42));
				SerializeField(s, nameof(float__43));
				SerializeField(s, nameof(float__44));
				SerializeField(s, nameof(float__45));
				SerializeField(s, nameof(float__46));
				SerializeField(s, nameof(float__47));
				SerializeField(s, nameof(float__48));
				SerializeField(s, nameof(float__49));
				SerializeField(s, nameof(float__50));
				SerializeField(s, nameof(float__51));
				SerializeField(s, nameof(int__52));
			} else {
				SerializeField(s, nameof(cameraLookAtOffsetYUp));
				SerializeField(s, nameof(cameraLookAtOffsetYDown));
				SerializeField(s, nameof(cameraLookAtOffset));
				SerializeField(s, nameof(cameraLookAtOffsetMaxInMulti));
				SerializeField(s, nameof(focale));
				SerializeField(s, nameof(ignoreZ));
				SerializeField(s, nameof(zoneScaleDepthMin));
				SerializeField(s, nameof(zoneScaleDepthMax));
				SerializeField(s, nameof(zoneScaleAtDepthMin));
				SerializeField(s, nameof(zoneScaleAtDepthMax));
				SerializeField(s, nameof(zoneScaleSpeed));
				SerializeField(s, nameof(cameraDecenteringOffsetAtSpeedMin));
				SerializeField(s, nameof(cameraDecenteringOffsetAtSpeedMax));
				SerializeField(s, nameof(cameraDecenteringSpeedMin));
				SerializeField(s, nameof(cameraDecenteringSpeedMax));
				SerializeField(s, nameof(cameraDecenteringBlendAtSpeedMin));
				SerializeField(s, nameof(cameraDecenteringBlendAtSpeedMax));
				SerializeField(s, nameof(cameraDecenteringInertieAtSpeedMin));
				SerializeField(s, nameof(cameraDecenteringInertieAtSpeedMax));
				SerializeField(s, nameof(cameraDecenteringSmooth));
				SerializeField(s, nameof(cameraDecenteringSubjectLookDirWeight));
				SerializeField(s, nameof(cameraDecenteringDepthMin));
				SerializeField(s, nameof(cameraDecenteringDepthMax));
				SerializeField(s, nameof(cameraMovingSpeedMin));
				SerializeField(s, nameof(cameraMovingSpeedMax));
				SerializeField(s, nameof(cameraMovingBlendAtSpeedMin));
				SerializeField(s, nameof(cameraMovingBlendAtSpeedMax));
				SerializeField(s, nameof(cameraMovingSmooth));
				SerializeField(s, nameof(cameraMovingBlendAccelerationJustSticked));
				SerializeField(s, nameof(rayCastScaleMax));
				SerializeField(s, nameof(lockPositionBlendOnEnter));
				SerializeField(s, nameof(lockPositionBlendOnExit));
				SerializeField(s, nameof(screenLimitUpSpeedMax));
				SerializeField(s, nameof(screenLimitUpScale));
				SerializeField(s, nameof(subjectWeightUnregisterDelay));
				SerializeField(s, nameof(subjectWeightRegisterDelay));
				SerializeField(s, nameof(subjectMainVisibilityHorizontal));
				SerializeField(s, nameof(subjectMainVisibilityVertical));
				SerializeField(s, nameof(cameraMovingSmoothCoeffForLeader));
				SerializeField(s, nameof(subjectMainVisibilitySwitchAxeSpeed));
				SerializeField(s, nameof(zoomBlendInMultiplayer));
				SerializeField(s, nameof(isMainSubject));
				SerializeField(s, nameof(isMainDRCPlayer));
				SerializeField(s, nameof(isLockedAxe));
				SerializeField(s, nameof(isFixed));
			}
		}
	}
}

