using UnityEngine;

namespace UbiArt.ITF {
	[Games(GameFlags.RA)]
	public partial class RLC_CreatureTreeManager_Template : TemplateObj {
		[Serialize("TreeTierList"                       )] public CList<RLC_CreatureTreeTier> TreeTierList;
		[Serialize("TreeTopShapeOffset"                 )] public float TreeTopShapeOffset;
		[Serialize("TreeTopPath"                        )] public Path TreeTopPath;
		[Serialize("TreePatchPath"                      )] public Path TreePatchPath;
		[Serialize("HouseCrownPath"                     )] public Path HouseCrownPath;
		[Serialize("TreeSignPath"                       )] public Path TreeSignPath;
		[Serialize("FamilySignPath"                     )] public Path FamilySignPath;
		[Serialize("FamilySignMediumPath"               )] public Path FamilySignMediumPath;
		[Serialize("FamilySignLargePath"                )] public Path FamilySignLargePath;
		[Serialize("FamilyInfobuttonPath"               )] public Path FamilyInfobuttonPath;
		[Serialize("FamilyPowerupIconPath"              )] public Path FamilyPowerupIconPath;
		[Serialize("FamilyInfobuttonOffsetSmallPannel"  )] public Vec3d FamilyInfobuttonOffsetSmallPannel;
		[Serialize("FamilyInfobuttonOffsetMediumPannel" )] public Vec3d FamilyInfobuttonOffsetMediumPannel;
		[Serialize("FamilyInfobuttonOffsetBigPannel"    )] public Vec3d FamilyInfobuttonOffsetBigPannel;
		[Serialize("FamilyPowerupIconOffsetSmallPannel" )] public Vec3d FamilyPowerupIconOffsetSmallPannel;
		[Serialize("FamilyPowerupIconOffsetMediumPannel")] public Vec3d FamilyPowerupIconOffsetMediumPannel;
		[Serialize("FamilyPowerupIconOffsetBigPannel"   )] public Vec3d FamilyPowerupIconOffsetBigPannel;
		[Serialize("EnergyBallPath"                     )] public Path EnergyBallPath;
		[Serialize("FlowerPowerPath"                    )] public Path FlowerPowerPath;
		[Serialize("EnergyBallUncoPath"                 )] public Path EnergyBallUncoPath;
		[Serialize("FlowerPowerUncoPath"                )] public Path FlowerPowerUncoPath;
		[Serialize("EnergyBallRarePath"                 )] public Path EnergyBallRarePath;
		[Serialize("FlowerPowerRarePath"                )] public Path FlowerPowerRarePath;
		[Serialize("EnergyBallQueenPath"                )] public Path EnergyBallQueenPath;
		[Serialize("FlowerPowerQueenPath"               )] public Path FlowerPowerQueenPath;
		[Serialize("GemPath"                            )] public Path GemPath;
		[Serialize("RegionPath"                         )] public Path RegionPath;
		[Serialize("CostumePath"                        )] public Path CostumePath;
		[Serialize("Ritual_SpeedCamera"                 )] public float Ritual_SpeedCamera;
		[Serialize("Ritual_DelaiShakeBeforeGrowth"      )] public float Ritual_DelaiShakeBeforeGrowth;
		[Serialize("Ritual_DelaiBeforeLaunchRitual"     )] public float Ritual_DelaiBeforeLaunchRitual;
		[Serialize("Ritual_RewardCreatureOffset"        )] public Vec3d Ritual_RewardCreatureOffset;
		[Serialize("Ritual_CreatureOnTopOfTheTreeOffset")] public Vec3d Ritual_CreatureOnTopOfTheTreeOffset;
		[Serialize("Ritual_CreatureBeforeRitual"        )] public Vec3d Ritual_CreatureBeforeRitual;
		[Serialize("Ritual_RitualTimeCelebration"       )] public float Ritual_RitualTimeCelebration;
		[Serialize("Ritual_DelaiRewardPopupisDisplayed" )] public float Ritual_DelaiRewardPopupisDisplayed;
		[Serialize("StarStepInMeters"                   )] public float StarStepInMeters;
		[Serialize("StarNeededToGrowBranches"           )] public uint StarNeededToGrowBranches;
		[Serialize("SmallHouseMaxMember"                )] public uint SmallHouseMaxMember;
		[Serialize("RewardsList"                        )] public CMap<int, RLC_TreeRewardList> RewardsList;
		[Serialize("LevelXPList"                        )] public CList<uint> LevelXPList;
		[Serialize("PropsTrunkMidList"                  )] public CList<Path> PropsTrunkMidList;
		[Serialize("PropsTrunkBorderList"               )] public CList<Path> PropsTrunkBorderList;
		[Serialize("XPSpeed"                            )] public uint XPSpeed;
		[Serialize("XPMultiplier"                       )] public uint XPMultiplier;
		[Serialize("GrabCreatureTouchDuration"          )] public float GrabCreatureTouchDuration;
		[Serialize("LaunchCreatureMaxSpeed"             )] public float LaunchCreatureMaxSpeed;
		[Serialize("TreeTrunckScale"                    )] public float TreeTrunckScale;
		[Serialize("OffsetByFamilly"                    )] public float OffsetByFamilly;
		[Serialize("BeatboxTutoIconStart"               )] public PathRef BeatboxTutoIconStart;
		[Serialize("BeatboxTutoIconStop"                )] public PathRef BeatboxTutoIconStop;
		[Serialize("BeatboxTutoIconSave"                )] public PathRef BeatboxTutoIconSave;
		[Serialize("WwiseGUID_StartFocus"               )] public StringID WwiseGUID_StartFocus;
		[Serialize("WwiseGUID_StopFocus"                )] public StringID WwiseGUID_StopFocus;
		[Serialize("PreloadDistance"                    )] public float PreloadDistance;
		[Serialize("LoadDistance"                       )] public float LoadDistance;
		[Serialize("FX_LeaveCommon"                     )] public Path FX_LeaveCommon;
		[Serialize("FX_LeaveUncommon"                   )] public Path FX_LeaveUncommon;
		[Serialize("FX_LeaveRare"                       )] public Path FX_LeaveRare;
		[Serialize("FX_LeaveQueen"                      )] public Path FX_LeaveQueen;
		[Serialize("FX_LeaveDeath"                      )] public Path FX_LeaveDeath;
		[Serialize("TreeOptimGraphList"                 )] public CList<RLC_TreeOptimGraph> TreeOptimGraphList;
		[Serialize("FXGiftPath"                         )] public Path FXGiftPath;
		[Serialize("FXGiftRegionPath"                   )] public Path FXGiftRegionPath;
		[Serialize("FXGiftCostumePath"                  )] public Path FXGiftCostumePath;
		[Serialize("FXLevelPath"                        )] public Path FXLevelPath;
		[Serialize("FXLevelExploPath"                   )] public Path FXLevelExploPath;
		[Serialize("BeatBoxTapFxPath"                   )] public Path BeatBoxTapFxPath;
		[Serialize("BeatBoxRecDefault"                  )] public bool BeatBoxRecDefault;
		[Serialize("BeatBoxDisplayUI"                   )] public bool BeatBoxDisplayUI;
		[Serialize("BeatBoxRecLengthFactor"             )] public float BeatBoxRecLengthFactor;
		[Serialize("BeatBoxTutoNextSteps"               )] public CMap<string, string> BeatBoxTutoNextSteps;
		[Serialize("BeatboxTutoNbCreaturesToUnlock"     )] public uint BeatboxTutoNbCreaturesToUnlock;
		[Serialize("BeatboxTutoNbCreaturesForReminder"  )] public uint BeatboxTutoNbCreaturesForReminder;
		[Serialize("TutoLeaderboardMinAdventure"        )] public uint TutoLeaderboardMinAdventure;
		protected override void SerializeImpl(CSerializerObject s) {
			base.SerializeImpl(s);
			SerializeField(s, nameof(TreeTierList));
			SerializeField(s, nameof(TreeTopShapeOffset));
			SerializeField(s, nameof(TreeTopPath));
			SerializeField(s, nameof(TreePatchPath));
			SerializeField(s, nameof(HouseCrownPath));
			SerializeField(s, nameof(TreeSignPath));
			SerializeField(s, nameof(FamilySignPath));
			SerializeField(s, nameof(FamilySignMediumPath));
			SerializeField(s, nameof(FamilySignLargePath));
			SerializeField(s, nameof(FamilyInfobuttonPath));
			SerializeField(s, nameof(FamilyPowerupIconPath));
			SerializeField(s, nameof(FamilyInfobuttonOffsetSmallPannel));
			SerializeField(s, nameof(FamilyInfobuttonOffsetMediumPannel));
			SerializeField(s, nameof(FamilyInfobuttonOffsetBigPannel));
			SerializeField(s, nameof(FamilyPowerupIconOffsetSmallPannel));
			SerializeField(s, nameof(FamilyPowerupIconOffsetMediumPannel));
			SerializeField(s, nameof(FamilyPowerupIconOffsetBigPannel));
			SerializeField(s, nameof(EnergyBallPath));
			SerializeField(s, nameof(FlowerPowerPath));
			SerializeField(s, nameof(EnergyBallUncoPath));
			SerializeField(s, nameof(FlowerPowerUncoPath));
			SerializeField(s, nameof(EnergyBallRarePath));
			SerializeField(s, nameof(FlowerPowerRarePath));
			SerializeField(s, nameof(EnergyBallQueenPath));
			SerializeField(s, nameof(FlowerPowerQueenPath));
			SerializeField(s, nameof(GemPath));
			SerializeField(s, nameof(RegionPath));
			SerializeField(s, nameof(CostumePath));
			SerializeField(s, nameof(Ritual_SpeedCamera));
			SerializeField(s, nameof(Ritual_DelaiShakeBeforeGrowth));
			SerializeField(s, nameof(Ritual_DelaiBeforeLaunchRitual));
			SerializeField(s, nameof(Ritual_RewardCreatureOffset));
			SerializeField(s, nameof(Ritual_CreatureOnTopOfTheTreeOffset));
			SerializeField(s, nameof(Ritual_CreatureBeforeRitual));
			SerializeField(s, nameof(Ritual_RitualTimeCelebration));
			SerializeField(s, nameof(Ritual_DelaiRewardPopupisDisplayed));
			SerializeField(s, nameof(StarStepInMeters));
			SerializeField(s, nameof(StarNeededToGrowBranches));
			SerializeField(s, nameof(SmallHouseMaxMember));
			SerializeField(s, nameof(RewardsList));
			SerializeField(s, nameof(LevelXPList));
			SerializeField(s, nameof(PropsTrunkMidList));
			SerializeField(s, nameof(PropsTrunkBorderList));
			SerializeField(s, nameof(XPSpeed));
			SerializeField(s, nameof(XPMultiplier));
			SerializeField(s, nameof(GrabCreatureTouchDuration));
			SerializeField(s, nameof(LaunchCreatureMaxSpeed));
			SerializeField(s, nameof(TreeTrunckScale));
			SerializeField(s, nameof(OffsetByFamilly));
			SerializeField(s, nameof(BeatboxTutoIconStart));
			SerializeField(s, nameof(BeatboxTutoIconStop));
			SerializeField(s, nameof(BeatboxTutoIconSave));
			SerializeField(s, nameof(WwiseGUID_StartFocus));
			SerializeField(s, nameof(WwiseGUID_StopFocus));
			SerializeField(s, nameof(PreloadDistance));
			SerializeField(s, nameof(LoadDistance));
			SerializeField(s, nameof(FX_LeaveCommon));
			SerializeField(s, nameof(FX_LeaveUncommon));
			SerializeField(s, nameof(FX_LeaveRare));
			SerializeField(s, nameof(FX_LeaveQueen));
			SerializeField(s, nameof(FX_LeaveDeath));
			SerializeField(s, nameof(TreeOptimGraphList));
			SerializeField(s, nameof(FXGiftPath));
			SerializeField(s, nameof(FXGiftRegionPath));
			SerializeField(s, nameof(FXGiftCostumePath));
			SerializeField(s, nameof(FXLevelPath));
			SerializeField(s, nameof(FXLevelExploPath));
			SerializeField(s, nameof(BeatBoxTapFxPath));
			SerializeField(s, nameof(BeatBoxRecDefault));
			SerializeField(s, nameof(BeatBoxDisplayUI));
			SerializeField(s, nameof(BeatBoxRecLengthFactor));
			SerializeField(s, nameof(BeatBoxTutoNextSteps));
			SerializeField(s, nameof(BeatboxTutoNbCreaturesToUnlock));
			SerializeField(s, nameof(BeatboxTutoNbCreaturesForReminder));
			SerializeField(s, nameof(TutoLeaderboardMinAdventure));
		}
		public override uint? ClassCRC => 0x154D6824;
	}
}

