using UnityEngine;

namespace UbiArt.ITF {
	[Games(GameFlags.RA)]
	public partial class RLC_InAppPurchaseManager_Template : TemplateObj {
		[Serialize("Reward_BronzeCup"                       )] public RLC_ScoreRecapReward Reward_BronzeCup;
		[Serialize("Reward_SilverCup"                       )] public RLC_ScoreRecapReward Reward_SilverCup;
		[Serialize("Reward_GoldCup"                         )] public RLC_ScoreRecapReward Reward_GoldCup;
		[Serialize("Reward_BronzeCupHard"                   )] public RLC_ScoreRecapReward Reward_BronzeCupHard;
		[Serialize("Reward_SilverCupHard"                   )] public RLC_ScoreRecapReward Reward_SilverCupHard;
		[Serialize("Reward_GoldCupHard"                     )] public RLC_ScoreRecapReward Reward_GoldCupHard;
		[Serialize("Reward_decoyBronzeDefault"              )] public RLC_ScoreRecapReward Reward_decoyBronzeDefault;
		[Serialize("Reward_decoySilverDefault"              )] public RLC_ScoreRecapReward Reward_decoySilverDefault;
		[Serialize("Reward_decoyGoldDefault"                )] public RLC_ScoreRecapReward Reward_decoyGoldDefault;
		[Serialize("Reward_decoyIntro"                      )] public RLC_ScoreRecapReward Reward_decoyIntro;
		[Serialize("Price_OneFood"                          )] public uint Price_OneFood;
		[Serialize("Price_ChangeObjective"                  )] public uint Price_ChangeObjective;
		[Serialize("Price_InstantPowerup"                   )] public uint Price_InstantPowerup;
		[Serialize("Price_MagnifyingGlass"                  )] public uint Price_MagnifyingGlass;
		[Serialize("SpeedRunAddTimePriceWithGems"           )] public uint SpeedRunAddTimePriceWithGems;
		[Serialize("SpeedRunAddTimeTimeWithGems"            )] public uint SpeedRunAddTimeTimeWithGems;
		[Serialize("SpeedRunAddTimeTimeWithVideo"           )] public uint SpeedRunAddTimeTimeWithVideo;
		[Serialize("Price_Elixir_CommonToUnco"              )] public uint Price_Elixir_CommonToUnco;
		[Serialize("Price_Elixir_UncoToRare"                )] public uint Price_Elixir_UncoToRare;
		[Serialize("Shop_Costumes_Barbara"                  )] public CList<RLC_ShopCostume> Shop_Costumes_Barbara;
		[Serialize("Shop_Costumes_Globox"                   )] public CList<RLC_ShopCostume> Shop_Costumes_Globox;
		[Serialize("Shop_Costumes_Rayman"                   )] public CList<RLC_ShopCostume> Shop_Costumes_Rayman;
		[Serialize("Shop_Costumes_Teensy"                   )] public CList<RLC_ShopCostume> Shop_Costumes_Teensy;
		[Serialize("IconRayman"                             )] public Path IconRayman;
		[Serialize("IconBarbara"                            )] public Path IconBarbara;
		[Serialize("IconGlobox"                             )] public Path IconGlobox;
		[Serialize("IconTeensy"                             )] public Path IconTeensy;
		[Serialize("CostumeScrollingButton"                 )] public Path CostumeScrollingButton;
		[Serialize("ElixirTypesOrderedForShop"              )] public CList<RLC_ElixirType> ElixirTypesOrderedForShop;
		[Serialize("LuckyTicketRewardSquare"                )] public PathRef LuckyTicketRewardSquare;
		[Serialize("LuckyTicketRewardGems"                  )] public PathRef LuckyTicketRewardGems;
		[Serialize("luckyTicketRewardEgg"                   )] public PathRef luckyTicketRewardEgg;
		[Serialize("LuckyTicketRewardFood"                  )] public PathRef LuckyTicketRewardFood;
		[Serialize("LuckyTicketRewardGoldenTicket"          )] public PathRef LuckyTicketRewardGoldenTicket;
		[Serialize("LuckyTicketRewardElixir"                )] public PathRef LuckyTicketRewardElixir;
		[Serialize("LuckyTicketRewardElixirX2"              )] public PathRef LuckyTicketRewardElixirX2;
		[Serialize("LuckyTicketRewardElixirX3"              )] public PathRef LuckyTicketRewardElixirX3;
		[Serialize("LuckyTicketRewardAllElixirPack"         )] public PathRef LuckyTicketRewardAllElixirPack;
		[Serialize("LuckyTicketRewardMagnifyingGlass"       )] public PathRef LuckyTicketRewardMagnifyingGlass;
		[Serialize("LuckyTicketRewardChallengeToken"        )] public PathRef LuckyTicketRewardChallengeToken;
		[Serialize("LuckyTicketRewardEasterEgg"             )] public PathRef LuckyTicketRewardEasterEgg;
		[Serialize("LuckyTicketRewardEasterEgg01"           )] public PathRef LuckyTicketRewardEasterEgg01;
		[Serialize("LuckyTicketRewardEasterEgg02"           )] public PathRef LuckyTicketRewardEasterEgg02;
		[Serialize("LuckyTicketRewardEasterEgg03"           )] public PathRef LuckyTicketRewardEasterEgg03;
		[Serialize("LuckyTicketRewardEasterEgg04"           )] public PathRef LuckyTicketRewardEasterEgg04;
		[Serialize("LuckyTicketTileRevealPercent"           )] public float LuckyTicketTileRevealPercent;
		[Serialize("MenuLuckyTicketRewardDiskIcon"          )] public Path MenuLuckyTicketRewardDiskIcon;
		[Serialize("duplicateGaugeBannerLeftPath"           )] public PathRef duplicateGaugeBannerLeftPath;
		[Serialize("duplicateGaugeBannerRightPath"          )] public PathRef duplicateGaugeBannerRightPath;
		[Serialize("WwiseGUID_ShopEnter"                    )] public StringID WwiseGUID_ShopEnter;
		[Serialize("WwiseGUID_ShopExit"                     )] public StringID WwiseGUID_ShopExit;
		[Serialize("StarterPackAvailabilityInterval"        )] public online.TimeInterval StarterPackAvailabilityInterval;
		[Serialize("StarterPackTimeBetweenForcedPopups"     )] public online.TimeInterval StarterPackTimeBetweenForcedPopups;
		[Serialize("StoreBundleUIData2"                     )] public CMap<RLC_StoreBundle.Type, RLC_StoreBundleUIData> StoreBundleUIData2;
		[Serialize("RewardedVideoGemsNb"                    )] public uint RewardedVideoGemsNb;
		[Serialize("RewardedVideoFoodNb"                    )] public uint RewardedVideoFoodNb;
		[Serialize("RewardedVideoSeasonalCurrencyNb"        )] public uint RewardedVideoSeasonalCurrencyNb;
		[Serialize("RewardedVideoChallengeTokenNb"          )] public uint RewardedVideoChallengeTokenNb;
		[Serialize("GemGiftAmountBeforeShop"                )] public uint GemGiftAmountBeforeShop;
		[Serialize("SecondLuckyTicketReward"                )] public RLC_LuckyTicketReward SecondLuckyTicketReward;
		[Serialize("NbNewElixirsGivenInDialog"              )] public uint NbNewElixirsGivenInDialog;
		[Serialize("showCostumePricesOnButtons"             )] public bool showCostumePricesOnButtons;
		[Serialize("automaticPopupWhenUsingLastFoodInRunner")] public bool automaticPopupWhenUsingLastFoodInRunner;
		[Serialize("automaticPopupWhenUsingLastFoodInTree"  )] public bool automaticPopupWhenUsingLastFoodInTree;
		[Serialize("automaticPopupWhenUsingLastSpeedElixir" )] public bool automaticPopupWhenUsingLastSpeedElixir;
		[Serialize("ticketCategoryWeightsSimple"            )] public CMap<uint, RLC_LuckyTicketCategoryWeight> ticketCategoryWeightsSimple;
		[Serialize("ticketCategoryWeightsGolden"            )] public CMap<uint, RLC_LuckyTicketCategoryWeight> ticketCategoryWeightsGolden;
		[Serialize("ticketCategoryWeightsChocolate"         )] public CMap<uint, RLC_LuckyTicketCategoryWeight> ticketCategoryWeightsChocolate;
		[Serialize("ticketNormalRewardWeightsSimple"        )] public CMap<uint, RLC_LuckyTicketRewardWeight> ticketNormalRewardWeightsSimple;
		[Serialize("ticketNormalRewardWeightsGolden"        )] public CMap<uint, RLC_LuckyTicketRewardWeight> ticketNormalRewardWeightsGolden;
		[Serialize("ticketNormalRewardWeightsChocolate"     )] public CMap<uint, RLC_LuckyTicketRewardWeight> ticketNormalRewardWeightsChocolate;
		[Serialize("ticketJackpotRewardWeightsSimple"       )] public CMap<uint, RLC_LuckyTicketRewardWeight> ticketJackpotRewardWeightsSimple;
		[Serialize("ticketJackpotRewardWeightsGolden"       )] public CMap<uint, RLC_LuckyTicketRewardWeight> ticketJackpotRewardWeightsGolden;
		[Serialize("ticketJackpotRewardWeightsChocolate"    )] public CMap<uint, RLC_LuckyTicketRewardWeight> ticketJackpotRewardWeightsChocolate;
		[Serialize("ticketEggRarityWeightsSimple"           )] public CMap<uint, RLC_CreatureRarityWeight> ticketEggRarityWeightsSimple;
		[Serialize("ticketEggRarityWeightsGolden"           )] public CMap<uint, RLC_CreatureRarityWeight> ticketEggRarityWeightsGolden;
		[Serialize("ticketEggRarityWeightsChocolate"        )] public CMap<uint, RLC_CreatureRarityWeight> ticketEggRarityWeightsChocolate;
		[Serialize("DailyRewards"                           )] public CMap<uint, RLC_LuckyTicketReward> DailyRewards;
		[Serialize("DailyRewardFoodMaximumForSwitchToFood"  )] public uint DailyRewardFoodMaximumForSwitchToFood;
		[Serialize("DailyRewardCanSwitchToFood"             )] public bool DailyRewardCanSwitchToFood;
		[Serialize("PromotedCostumeVersions"                )] public CMap<uint, RLC_ShopCostumeVersion> PromotedCostumeVersions;
		[Serialize("unlockShopAdventureSequence"            )] public uint unlockShopAdventureSequence;
		[Serialize("unlockShopCompletedMapsCount"           )] public uint unlockShopCompletedMapsCount;
		[Serialize("tutoShopAdventureSequence"              )] public uint tutoShopAdventureSequence;
		[Serialize("tutoShopCompletedMapsCount"             )] public uint tutoShopCompletedMapsCount;
		[Serialize("displayGloboxCostumes"                  )] public bool displayGloboxCostumes;
		[Serialize("displayTeensyCostumes"                  )] public bool displayTeensyCostumes;
		[Serialize("iapScores"                              )] public CMap<StringID, uint> iapScores;
		[Serialize("allowScoreRecapVideoReward"             )] public bool allowScoreRecapVideoReward;
		[Serialize("Reward_ScoreRecapVideoDefault"          )] public RLC_ScoreRecapReward Reward_ScoreRecapVideoDefault;
		[Serialize("support_iOS8"                           )] public bool support_iOS8;
		[Serialize("DynamicPackSlotItem"                    )] public Path DynamicPackSlotItem;
		protected override void SerializeImpl(CSerializerObject s) {
			base.SerializeImpl(s);
			SerializeField(s, nameof(Reward_BronzeCup));
			SerializeField(s, nameof(Reward_SilverCup));
			SerializeField(s, nameof(Reward_GoldCup));
			SerializeField(s, nameof(Reward_BronzeCupHard));
			SerializeField(s, nameof(Reward_SilverCupHard));
			SerializeField(s, nameof(Reward_GoldCupHard));
			SerializeField(s, nameof(Reward_decoyBronzeDefault));
			SerializeField(s, nameof(Reward_decoySilverDefault));
			SerializeField(s, nameof(Reward_decoyGoldDefault));
			SerializeField(s, nameof(Reward_decoyIntro));
			SerializeField(s, nameof(Price_OneFood));
			SerializeField(s, nameof(Price_ChangeObjective));
			SerializeField(s, nameof(Price_InstantPowerup));
			SerializeField(s, nameof(Price_MagnifyingGlass));
			SerializeField(s, nameof(SpeedRunAddTimePriceWithGems));
			SerializeField(s, nameof(SpeedRunAddTimeTimeWithGems));
			SerializeField(s, nameof(SpeedRunAddTimeTimeWithVideo));
			SerializeField(s, nameof(Price_Elixir_CommonToUnco));
			SerializeField(s, nameof(Price_Elixir_UncoToRare));
			SerializeField(s, nameof(Shop_Costumes_Barbara));
			SerializeField(s, nameof(Shop_Costumes_Globox));
			SerializeField(s, nameof(Shop_Costumes_Rayman));
			SerializeField(s, nameof(Shop_Costumes_Teensy));
			SerializeField(s, nameof(IconRayman));
			SerializeField(s, nameof(IconBarbara));
			SerializeField(s, nameof(IconGlobox));
			SerializeField(s, nameof(IconTeensy));
			SerializeField(s, nameof(CostumeScrollingButton));
			SerializeField(s, nameof(ElixirTypesOrderedForShop));
			SerializeField(s, nameof(LuckyTicketRewardSquare));
			SerializeField(s, nameof(LuckyTicketRewardGems));
			SerializeField(s, nameof(luckyTicketRewardEgg));
			SerializeField(s, nameof(LuckyTicketRewardFood));
			SerializeField(s, nameof(LuckyTicketRewardGoldenTicket));
			SerializeField(s, nameof(LuckyTicketRewardElixir));
			SerializeField(s, nameof(LuckyTicketRewardElixirX2));
			SerializeField(s, nameof(LuckyTicketRewardElixirX3));
			SerializeField(s, nameof(LuckyTicketRewardAllElixirPack));
			SerializeField(s, nameof(LuckyTicketRewardMagnifyingGlass));
			SerializeField(s, nameof(LuckyTicketRewardChallengeToken));
			SerializeField(s, nameof(LuckyTicketRewardEasterEgg));
			SerializeField(s, nameof(LuckyTicketRewardEasterEgg01));
			SerializeField(s, nameof(LuckyTicketRewardEasterEgg02));
			SerializeField(s, nameof(LuckyTicketRewardEasterEgg03));
			SerializeField(s, nameof(LuckyTicketRewardEasterEgg04));
			SerializeField(s, nameof(LuckyTicketTileRevealPercent));
			SerializeField(s, nameof(MenuLuckyTicketRewardDiskIcon));
			SerializeField(s, nameof(duplicateGaugeBannerLeftPath));
			SerializeField(s, nameof(duplicateGaugeBannerRightPath));
			SerializeField(s, nameof(WwiseGUID_ShopEnter));
			SerializeField(s, nameof(WwiseGUID_ShopExit));
			SerializeField(s, nameof(StarterPackAvailabilityInterval));
			SerializeField(s, nameof(StarterPackTimeBetweenForcedPopups));
			SerializeField(s, nameof(StoreBundleUIData2));
			SerializeField(s, nameof(RewardedVideoGemsNb));
			SerializeField(s, nameof(RewardedVideoFoodNb));
			SerializeField(s, nameof(RewardedVideoSeasonalCurrencyNb));
			SerializeField(s, nameof(RewardedVideoChallengeTokenNb));
			SerializeField(s, nameof(GemGiftAmountBeforeShop));
			SerializeField(s, nameof(SecondLuckyTicketReward));
			SerializeField(s, nameof(NbNewElixirsGivenInDialog));
			SerializeField(s, nameof(showCostumePricesOnButtons));
			SerializeField(s, nameof(automaticPopupWhenUsingLastFoodInRunner));
			SerializeField(s, nameof(automaticPopupWhenUsingLastFoodInTree));
			SerializeField(s, nameof(automaticPopupWhenUsingLastSpeedElixir));
			SerializeField(s, nameof(ticketCategoryWeightsSimple));
			SerializeField(s, nameof(ticketCategoryWeightsGolden));
			SerializeField(s, nameof(ticketCategoryWeightsChocolate));
			SerializeField(s, nameof(ticketNormalRewardWeightsSimple));
			SerializeField(s, nameof(ticketNormalRewardWeightsGolden));
			SerializeField(s, nameof(ticketNormalRewardWeightsChocolate));
			SerializeField(s, nameof(ticketJackpotRewardWeightsSimple));
			SerializeField(s, nameof(ticketJackpotRewardWeightsGolden));
			SerializeField(s, nameof(ticketJackpotRewardWeightsChocolate));
			SerializeField(s, nameof(ticketEggRarityWeightsSimple));
			SerializeField(s, nameof(ticketEggRarityWeightsGolden));
			SerializeField(s, nameof(ticketEggRarityWeightsChocolate));
			SerializeField(s, nameof(DailyRewards));
			SerializeField(s, nameof(DailyRewardFoodMaximumForSwitchToFood));
			SerializeField(s, nameof(DailyRewardCanSwitchToFood));
			SerializeField(s, nameof(PromotedCostumeVersions));
			SerializeField(s, nameof(unlockShopAdventureSequence));
			SerializeField(s, nameof(unlockShopCompletedMapsCount));
			SerializeField(s, nameof(tutoShopAdventureSequence));
			SerializeField(s, nameof(tutoShopCompletedMapsCount));
			SerializeField(s, nameof(displayGloboxCostumes));
			SerializeField(s, nameof(displayTeensyCostumes));
			SerializeField(s, nameof(iapScores));
			SerializeField(s, nameof(allowScoreRecapVideoReward));
			SerializeField(s, nameof(Reward_ScoreRecapVideoDefault));
			SerializeField(s, nameof(support_iOS8));
			SerializeField(s, nameof(DynamicPackSlotItem));
		}
		public override uint? ClassCRC => 0xB0808422;
	}
}

