using UnityEngine;

namespace UbiArt.ITF {
	public partial class RO2_SpikyShellTrapComponent_Template : ActorComponent_Template {
		[Serialize("spikeMaterial"                   )] public GFXMaterialSerializable spikeMaterial;
		[Serialize("spikeWidth"                      )] public float spikeWidth;
		[Serialize("spikeHeight"                     )] public float spikeHeight;
		[Serialize("spikeHeightOffsetDown"           )] public float spikeHeightOffsetDown;
		[Serialize("spikeHeightOffsetUp"             )] public float spikeHeightOffsetUp;
		[Serialize("baseWidth"                       )] public float baseWidth;
		[Serialize("baseHeight"                      )] public float baseHeight;
		[Serialize("baseHeightOffset"                )] public float baseHeightOffset;
		[Serialize("minScaleFactor"                  )] public float minScaleFactor;
		[Serialize("minSpacing"                      )] public float minSpacing;
		[Serialize("maxSpacing"                      )] public float maxSpacing;
		[Serialize("restHeightPercent"               )] public float restHeightPercent;
		[Serialize("shakeHeightPercent"              )] public float shakeHeightPercent;
		[Serialize("risenHeightPercent"              )] public float risenHeightPercent;
		[Serialize("frontBaseTexIndex_Idle"          )] public uint frontBaseTexIndex_Idle;
		[Serialize("frontBaseFirstTexIndex_Shaking"  )] public uint frontBaseFirstTexIndex_Shaking;
		[Serialize("frontBaseLastTexIndex_Shaking"   )] public uint frontBaseLastTexIndex_Shaking;
		[Serialize("backBaseTexIndex_Idle"           )] public uint backBaseTexIndex_Idle;
		[Serialize("backBaseFirstTexIndex_Shaking"   )] public uint backBaseFirstTexIndex_Shaking;
		[Serialize("spikeFirstTexIndex"              )] public uint spikeFirstTexIndex;
		[Serialize("spikeLastTexIndex"               )] public uint spikeLastTexIndex;
		[Serialize("shakeDetectionRadius"            )] public float shakeDetectionRadius;
		[Serialize("spikeDetectionRadius"            )] public float spikeDetectionRadius;
		[Serialize("endOfSpikeDetectionRadius"       )] public float endOfSpikeDetectionRadius;
		[Serialize("faction"                         )] public uint faction;
		[Serialize("minAlertDuration"                )] public float minAlertDuration;
		[Serialize("minSpikeDuration"                )] public float minSpikeDuration;
		[Serialize("spikeYOffset"                    )] public float spikeYOffset;
		[Serialize("hitMarginPercent"                )] public float hitMarginPercent;
		[Serialize("hitLevel"                        )] public uint hitLevel;
		[Serialize("spikeAnimationFirstFrameDuration")] public float spikeAnimationFirstFrameDuration;
		[Serialize("spikeAnimationFrameDuration"     )] public float spikeAnimationFrameDuration;
		[Serialize("baseAnimationFrameDuration"      )] public float baseAnimationFrameDuration;
		[Serialize("spikeInertia_Out"                )] public float spikeInertia_Out;
		[Serialize("spikeInertia_EmergencyOut"       )] public float spikeInertia_EmergencyOut;
		[Serialize("spikeInertia_Holster"            )] public float spikeInertia_Holster;
		[Serialize("spikeDetectionRadius_Emergency"  )] public float spikeDetectionRadius_Emergency;
		[Serialize("spikeBounciness"                 )] public float spikeBounciness;
		[Serialize("sidesAngle"                      )] public Angle sidesAngle;
		[Serialize("hitWidthScale"                   )] public float hitWidthScale;
		[Serialize("rotationMargin"                  )] public Angle rotationMargin;
		[Serialize("syncRatio"                       )] public float syncRatio;
		[Serialize("syncOffset"                      )] public float syncOffset;
		[Serialize("syncIndexOffset"                 )] public float syncIndexOffset;
		[Serialize("useAdditionalSpikes"             )] public bool useAdditionalSpikes;
		protected override void SerializeImpl(CSerializerObject s) {
			base.SerializeImpl(s);
			SerializeField(s, nameof(spikeMaterial));
			SerializeField(s, nameof(spikeWidth));
			SerializeField(s, nameof(spikeHeight));
			SerializeField(s, nameof(spikeHeightOffsetDown));
			SerializeField(s, nameof(spikeHeightOffsetUp));
			SerializeField(s, nameof(baseWidth));
			SerializeField(s, nameof(baseHeight));
			SerializeField(s, nameof(baseHeightOffset));
			SerializeField(s, nameof(minScaleFactor));
			SerializeField(s, nameof(minSpacing));
			SerializeField(s, nameof(maxSpacing));
			SerializeField(s, nameof(restHeightPercent));
			SerializeField(s, nameof(shakeHeightPercent));
			SerializeField(s, nameof(risenHeightPercent));
			SerializeField(s, nameof(frontBaseTexIndex_Idle));
			SerializeField(s, nameof(frontBaseFirstTexIndex_Shaking));
			SerializeField(s, nameof(frontBaseLastTexIndex_Shaking));
			SerializeField(s, nameof(backBaseTexIndex_Idle));
			SerializeField(s, nameof(backBaseFirstTexIndex_Shaking));
			SerializeField(s, nameof(spikeFirstTexIndex));
			SerializeField(s, nameof(spikeLastTexIndex));
			SerializeField(s, nameof(shakeDetectionRadius));
			SerializeField(s, nameof(spikeDetectionRadius));
			SerializeField(s, nameof(endOfSpikeDetectionRadius));
			SerializeField(s, nameof(faction));
			SerializeField(s, nameof(minAlertDuration));
			SerializeField(s, nameof(minSpikeDuration));
			SerializeField(s, nameof(spikeYOffset));
			SerializeField(s, nameof(hitMarginPercent));
			SerializeField(s, nameof(hitLevel));
			SerializeField(s, nameof(spikeAnimationFirstFrameDuration));
			SerializeField(s, nameof(spikeAnimationFrameDuration));
			SerializeField(s, nameof(baseAnimationFrameDuration));
			SerializeField(s, nameof(spikeInertia_Out));
			SerializeField(s, nameof(spikeInertia_EmergencyOut));
			SerializeField(s, nameof(spikeInertia_Holster));
			SerializeField(s, nameof(spikeDetectionRadius_Emergency));
			SerializeField(s, nameof(spikeBounciness));
			SerializeField(s, nameof(sidesAngle));
			SerializeField(s, nameof(hitWidthScale));
			SerializeField(s, nameof(rotationMargin));
			SerializeField(s, nameof(syncRatio));
			SerializeField(s, nameof(syncOffset));
			SerializeField(s, nameof(syncIndexOffset));
			SerializeField(s, nameof(useAdditionalSpikes));
		}
		public override uint? ClassCRC => 0xF941D2A2;
	}
}

