using UnityEngine;

namespace UbiArt.ITF {
	[Games(GameFlags.VH)]
	public partial class W1W_Emile_Template : ActorComponent_Template {
		[Serialize("WithAnimStateMachine_Template__0")] public WithAnimStateMachine_Template WithAnimStateMachine_Template__0;
		[Serialize("float__1"                        )] public float float__1;
		[Serialize("float__2"                        )] public float float__2;
		[Serialize("float__3"                        )] public float float__3;
		[Serialize("float__4"                        )] public float float__4;
		[Serialize("float__5"                        )] public float float__5;
		[Serialize("float__6"                        )] public float float__6;
		[Serialize("float__7"                        )] public float float__7;
		[Serialize("float__8"                        )] public float float__8;
		[Serialize("float__9"                        )] public float float__9;
		[Serialize("float__10"                       )] public float float__10;
		[Serialize("float__11"                       )] public float float__11;
		[Serialize("float__12"                       )] public float float__12;
		[Serialize("float__13"                       )] public float float__13;
		[Serialize("float__14"                       )] public float float__14;
		[Serialize("float__15"                       )] public float float__15;
		[Serialize("float__16"                       )] public float float__16;
		[Serialize("float__17"                       )] public float float__17;
		[Serialize("float__18"                       )] public float float__18;
		[Serialize("float__19"                       )] public float float__19;
		[Serialize("float__20"                       )] public float float__20;
		[Serialize("float__21"                       )] public float float__21;
		[Serialize("float__22"                       )] public float float__22;
		[Serialize("float__23"                       )] public float float__23;
		[Serialize("float__24"                       )] public float float__24;
		[Serialize("float__25"                       )] public float float__25;
		[Serialize("float__26"                       )] public float float__26;
		[Serialize("float__27"                       )] public float float__27;
		[Serialize("Vector2__28"                     )] public Vector2 Vector2__28;
		[Serialize("float__29"                       )] public float float__29;
		[Serialize("float__30"                       )] public float float__30;
		[Serialize("float__31"                       )] public float float__31;
		[Serialize("Curve2D__32"                     )] public Curve2D Curve2D__32;
		[Serialize("StringID__33"                    )] public StringID StringID__33;
		[Serialize("StringID__34"                    )] public StringID StringID__34;
		[Serialize("Path__35"                        )] public Path Path__35;
		[Serialize("Path__36"                        )] public Path Path__36;
		[Serialize("Path__37"                        )] public Path Path__37;
		[Serialize("Path__38"                        )] public Path Path__38;
		[Serialize("Path__39"                        )] public Path Path__39;
		[Serialize("Path__40"                        )] public Path Path__40;
		[Serialize("Path__41"                        )] public Path Path__41;
		[Serialize("Vector2__42"                     )] public Vector2 Vector2__42;
		[Serialize("Color__43"                       )] public Color Color__43;
		[Serialize("Color__44"                       )] public Color Color__44;
		[Serialize("float__45"                       )] public float float__45;
		[Serialize("float__46"                       )] public float float__46;
		[Serialize("float__47"                       )] public float float__47;
		[Serialize("float__48"                       )] public float float__48;
		[Serialize("float__49"                       )] public float float__49;
		[Serialize("Vector2__50"                     )] public Vector2 Vector2__50;
		[Serialize("Vector2__51"                     )] public Vector2 Vector2__51;
		[Serialize("float__52"                       )] public float float__52;
		[Serialize("Vector2__53"                     )] public Vector2 Vector2__53;
		[Serialize("Path__54"                        )] public Path Path__54;
		protected override void SerializeImpl(CSerializerObject s) {
			base.SerializeImpl(s);
			SerializeField(s, nameof(WithAnimStateMachine_Template__0));
			SerializeField(s, nameof(float__1));
			SerializeField(s, nameof(float__2));
			SerializeField(s, nameof(float__3));
			SerializeField(s, nameof(float__4));
			SerializeField(s, nameof(float__5));
			SerializeField(s, nameof(float__6));
			SerializeField(s, nameof(float__7));
			SerializeField(s, nameof(float__8));
			SerializeField(s, nameof(float__9));
			SerializeField(s, nameof(float__10));
			SerializeField(s, nameof(float__11));
			SerializeField(s, nameof(float__12));
			SerializeField(s, nameof(float__13));
			SerializeField(s, nameof(float__14));
			SerializeField(s, nameof(float__15));
			SerializeField(s, nameof(float__16));
			SerializeField(s, nameof(float__17));
			SerializeField(s, nameof(float__18));
			SerializeField(s, nameof(float__19));
			SerializeField(s, nameof(float__20));
			SerializeField(s, nameof(float__21));
			SerializeField(s, nameof(float__22));
			SerializeField(s, nameof(float__23));
			SerializeField(s, nameof(float__24));
			SerializeField(s, nameof(float__25));
			SerializeField(s, nameof(float__26));
			SerializeField(s, nameof(float__27));
			SerializeField(s, nameof(Vector2__28));
			SerializeField(s, nameof(float__29));
			SerializeField(s, nameof(float__30));
			SerializeField(s, nameof(float__31));
			SerializeField(s, nameof(Curve2D__32));
			SerializeField(s, nameof(StringID__33));
			SerializeField(s, nameof(StringID__34));
			SerializeField(s, nameof(Path__35));
			SerializeField(s, nameof(Path__36));
			SerializeField(s, nameof(Path__37));
			SerializeField(s, nameof(Path__38));
			SerializeField(s, nameof(Path__39));
			SerializeField(s, nameof(Path__40));
			SerializeField(s, nameof(Path__41));
			SerializeField(s, nameof(Vector2__42));
			SerializeField(s, nameof(Color__43));
			SerializeField(s, nameof(Color__44));
			SerializeField(s, nameof(float__45));
			SerializeField(s, nameof(float__46));
			SerializeField(s, nameof(float__47));
			SerializeField(s, nameof(float__48));
			SerializeField(s, nameof(float__49));
			SerializeField(s, nameof(Vector2__50));
			SerializeField(s, nameof(Vector2__51));
			SerializeField(s, nameof(float__52));
			SerializeField(s, nameof(Vector2__53));
			SerializeField(s, nameof(Path__54));
		}
		public override uint? ClassCRC => 0x734C6562;
	}
}

