using UnityEngine;

namespace UbiArt.ITF {
	[Games(GameFlags.VH)]
	public partial class W1W_FirePatchAIComponent_Template : GraphicComponent_Template {
		[Serialize("float__0"                   )] public float float__0;
		[Serialize("float__1"                   )] public float float__1;
		[Serialize("float__2"                   )] public float float__2;
		[Serialize("float__3"                   )] public float float__3;
		[Serialize("float__4"                   )] public float float__4;
		[Serialize("float__5"                   )] public float float__5;
		[Serialize("float__6"                   )] public float float__6;
		[Serialize("float__7"                   )] public float float__7;
		[Serialize("float__8"                   )] public float float__8;
		[Serialize("float__9"                   )] public float float__9;
		[Serialize("uint__10"                   )] public uint uint__10;
		[Serialize("uint__11"                   )] public uint uint__11;
		[Serialize("float__12"                  )] public float float__12;
		[Serialize("float__13"                  )] public float float__13;
		[Serialize("float__14"                  )] public float float__14;
		[Serialize("float__15"                  )] public float float__15;
		[Serialize("uint__16"                   )] public uint uint__16;
		[Serialize("uint__17"                   )] public uint uint__17;
		[Serialize("uint__18"                   )] public uint uint__18;
		[Serialize("uint__19"                   )] public uint uint__19;
		[Serialize("uint__20"                   )] public uint uint__20;
		[Serialize("uint__21"                   )] public uint uint__21;
		[Serialize("uint__22"                   )] public uint uint__22;
		[Serialize("uint__23"                   )] public uint uint__23;
		[Serialize("uint__24"                   )] public uint uint__24;
		[Serialize("uint__25"                   )] public uint uint__25;
		[Serialize("uint__26"                   )] public uint uint__26;
		[Serialize("uint__27"                   )] public uint uint__27;
		[Serialize("bool__28"                   )] public bool bool__28;
		[Serialize("float__29"                  )] public float float__29;
		[Serialize("float__30"                  )] public float float__30;
		[Serialize("GFXMaterialSerializable__31")] public GFXMaterialSerializable GFXMaterialSerializable__31;
		[Serialize("GFXMaterialSerializable__32")] public GFXMaterialSerializable GFXMaterialSerializable__32;
		[Serialize("float__33"                  )] public float float__33;
		[Serialize("uint__34"                   )] public uint uint__34;
		[Serialize("float__35"                  )] public float float__35;
		[Serialize("float__36"                  )] public float float__36;
		[Serialize("float__37"                  )] public float float__37;
		[Serialize("float__38"                  )] public float float__38;
		[Serialize("float__39"                  )] public float float__39;
		[Serialize("float__40"                  )] public float float__40;
		[Serialize("float__41"                  )] public float float__41;
		[Serialize("float__42"                  )] public float float__42;
		[Serialize("float__43"                  )] public float float__43;
		[Serialize("float__44"                  )] public float float__44;
		[Serialize("uint__45"                   )] public uint uint__45;
		[Serialize("float__46"                  )] public float float__46;
		[Serialize("StringID__47"               )] public StringID StringID__47;
		[Serialize("StringID__48"               )] public StringID StringID__48;
		[Serialize("bool__49"                   )] public bool bool__49;
		[Serialize("bool__50"                   )] public bool bool__50;
		[Serialize("bool__51"                   )] public bool bool__51;
		[Serialize("uint__52"                   )] public uint uint__52;
		[Serialize("uint__53"                   )] public uint uint__53;
		[Serialize("bool__54"                   )] public bool bool__54;
		[Serialize("bool__55"                   )] public bool bool__55;
		protected override void SerializeImpl(CSerializerObject s) {
			base.SerializeImpl(s);
			SerializeField(s, nameof(float__0));
			SerializeField(s, nameof(float__1));
			SerializeField(s, nameof(float__2));
			SerializeField(s, nameof(float__3));
			SerializeField(s, nameof(float__4));
			SerializeField(s, nameof(float__5));
			SerializeField(s, nameof(float__6));
			SerializeField(s, nameof(float__7));
			SerializeField(s, nameof(float__8));
			SerializeField(s, nameof(float__9));
			SerializeField(s, nameof(uint__10));
			SerializeField(s, nameof(uint__11));
			SerializeField(s, nameof(float__12));
			SerializeField(s, nameof(float__13));
			SerializeField(s, nameof(float__14));
			SerializeField(s, nameof(float__15));
			SerializeField(s, nameof(uint__16));
			SerializeField(s, nameof(uint__17));
			SerializeField(s, nameof(uint__18));
			SerializeField(s, nameof(uint__19));
			SerializeField(s, nameof(uint__20));
			SerializeField(s, nameof(uint__21));
			SerializeField(s, nameof(uint__22));
			SerializeField(s, nameof(uint__23));
			SerializeField(s, nameof(uint__24));
			SerializeField(s, nameof(uint__25));
			SerializeField(s, nameof(uint__26));
			SerializeField(s, nameof(uint__27));
			SerializeField(s, nameof(bool__28));
			SerializeField(s, nameof(float__29));
			SerializeField(s, nameof(float__30));
			SerializeField(s, nameof(GFXMaterialSerializable__31));
			SerializeField(s, nameof(GFXMaterialSerializable__32));
			SerializeField(s, nameof(float__33));
			SerializeField(s, nameof(uint__34));
			SerializeField(s, nameof(float__35));
			SerializeField(s, nameof(float__36));
			SerializeField(s, nameof(float__37));
			SerializeField(s, nameof(float__38));
			SerializeField(s, nameof(float__39));
			SerializeField(s, nameof(float__40));
			SerializeField(s, nameof(float__41));
			SerializeField(s, nameof(float__42));
			SerializeField(s, nameof(float__43));
			SerializeField(s, nameof(float__44));
			SerializeField(s, nameof(uint__45));
			SerializeField(s, nameof(float__46));
			SerializeField(s, nameof(StringID__47));
			SerializeField(s, nameof(StringID__48));
			SerializeField(s, nameof(bool__49));
			SerializeField(s, nameof(bool__50));
			SerializeField(s, nameof(bool__51));
			SerializeField(s, nameof(uint__52));
			SerializeField(s, nameof(uint__53));
			SerializeField(s, nameof(bool__54));
			SerializeField(s, nameof(bool__55));
		}
		public override uint? ClassCRC => 0x8A65CD69;
	}
}

